# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: 'Default'
  demands:
  - Agent.OS -equals Linux

steps:
- script: echo Hello, world!
- bash: echo $(Build.BuildNumber)
- bash: echo $(Agent.OS)
- bash: echo $(Build.ArtifactStagingDirectory)
- bash: echo $(Build.SourcesDirectory)
- bash: echo $(Build.StagingDirectory)
- bash: echo $(System.DefaultWorkingDirectory)
- bash: echo $(Build.Repository.Provider)
- bash: java -version
- bash: node -version
